# Generated by Django 5.0.3 on 2024-05-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0003_surveyresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid')], default='UNPAID', max_length=10),
        ),
        migrations.AlterField(
            model_name='resident',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
