# Generated by Django 5.0.3 on 2024-06-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0005_alter_bill_amount_alter_resident_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
