# Generated by Django 5.0.3 on 2024-07-14 14:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0007_alter_bill_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
