# Generated by Django 5.0.3 on 2024-07-17 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0009_product_cart_cartproduct_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
