# Generated by Django 5.0.3 on 2024-07-18 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0013_alter_cart_resident_alter_cartproduct_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='resident',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
