# Generated by Django 5.0.3 on 2024-07-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0015_billproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='billproduct',
            name='status',
            field=models.CharField(choices=[('ĐANG CHỜ', 'Đang chờ'), ('PAID', 'Paid')], default='PENDING', max_length=10),
        ),
    ]
