# Generated by Django 5.0.3 on 2024-07-23 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0016_billproduct_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billproduct',
            name='status',
        ),
    ]
